### ISSUE TITLE
Since the May ASB update, the UL source became unbuildable

### ISSUE THREAD

**Issue by rik0612c** [TARKZiM/android_device_htc_e8#1]
After the May ASB update, the LineageOS-UL source became unbuildable. 

> [ 99% 228/229] finishing build rules ...
> FAILED:
> hardware/qcom-caf/wlan/wcnss-service/Android.mk: error: "wcnss_service (EXECUTAB
> LES android-arm) missing libqmiservices (SHARED_LIBRARIES android-arm)" 
> You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is inten
> tional, but that may defer real problems until later in the build.
> hardware/qcom-caf/wlan/wcnss-service/Android.mk: error: "wcnss_service (EXECUTAB
> LES android-arm) missing libqmi_cci (SHARED_LIBRARIES android-arm)" 
> You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is inten
> tional, but that may defer real problems until later in the build.
> hardware/qcom-caf/wlan/wcnss-service/Android.mk: error: "wcnss_service (EXECUTAB
> LES android-arm) missing libmdmdetect (SHARED_LIBRARIES android-arm)" 
> You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is inten
> tional, but that may defer real problems until later in the build.
> build/make/core/main.mk:1126: error: exiting from previous errors.
> 00:36:00 ckati failed with: exit status 1

I have no idea what to do, could you please give me some hints to solve this? Thank you TARKZiM.

**Comment by TARKZiM** [comment]
@rik0612c Do you have any solution yet?
I just got time to play with this old device.

**Comment by rik0612c** [comment]
> @rik0612c Do you have any solution yet? I just got time to play with this old device.

I temporarily removed wcnss_service in device.mk and switched to prebuilt binary. 
haven't build whole rom though, i will give it a try later. hope it works....

**Comment by TARKZiM** [comment]
I found a way to make it buildable, will upload changes after it's done.

**Comment by TARKZiM** [comment]
@rik0612c Try this
https://github.com/TARKZiM/android_device_htc_msm8974-common/commit/2d29dd3f6535cd5639e913dbb0c2a935cd299289

**Comment by rik0612c** [comment]
> @rik0612c Try this [TARKZiM/android_device_htc_msm8974-common@2d29dd3](https://github.com/TARKZiM/android_device_htc_msm8974-common/commit/2d29dd3f6535cd5639e913dbb0c2a935cd299289)

it works. thanks for your help.
